FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN make build

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin/./main .
COPY --from=builder /app/.env .
EXPOSE 3001
CMD ["./main"]
